# version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3000"

  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prom-config.yml:/etc/prometheus/prometheus.yaml
